events {
    worker_connections 1024;
}

http {
    # Définit la zone de limitation
    limit_req_zone $binary_remote_addr zone=apilimit:10m rate=10r/s;

    upstream iris-apis {
        server mlops-iris-api:8000;
    }

    server {
        listen 80;
        server_name localhost;
        return 301 https://$host$request_uri;
    }

    server {
        listen 443 ssl;
        server_name localhost;

        ssl_certificate /etc/nginx/certs/nginx.crt;
        ssl_certificate_key /etc/nginx/certs/nginx.key;
        ssl_protocols TLSv1.2 TLSv1.3;
        ssl_ciphers HIGH:!aNULL:!MD5;
        ssl_prefer_server_ciphers on;

        location /predict {
            auth_basic "API Acess Protected";
            auth_basic_user_file /etc/nginx/.htpasswd;

            # Applique la limitation au bloc `location /predict`
            limit_req zone=apilimit burst=5 nodelay;

            proxy_pass http://iris-apis;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        location /nginx_status {
        stub_status on; # Active le module stub_status
        access_log off; # Ne pas logguer les accès à cet endpoint
        allow localhost; # Autorise l'accès uniquement depuis localhost (l'exporter)
        allow 192.168.0.0/20; # Ou depuis le réseau Docker
        deny all; # Bloque tout autre accès
        }
    }
}